stage1:
    hostname: vapp01-stage-ext.duh-hosting.de
    user: quellwerke
    port: 22
    configFile: ~/.ssh/config
    identityFile: ~/.ssh/id_rsa
    forwardAgent: true
    multiplexing: true
    sshOptions:
        UserKnownHostsFile: /dev/null
        StrictHostKeyChecking: no
    stage: stage
    roles:
        - app
        - db
    deploy_path: /srv/stage.duh-hosting.de/mydh

stage2:
    hostname: vapp02-stage-ext.duh-hosting.de
    user: quellwerke
    port: 22
    configFile: ~/.ssh/config
    identityFile: ~/.ssh/id_rsa
    forwardAgent: true
    multiplexing: true
    sshOptions:
        UserKnownHostsFile: /dev/null
        StrictHostKeyChecking: no
    stage: stage
    roles:
        - app
        - db
    deploy_path: /srv/stage.duh-hosting.de/mydh

local:
    local: true
    deploy_path: /var/www/html/deployer
    stage: local
    keep_releases: 1
